name: Check for updates

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      need-update: ${{ steps.close-issue.outputs.num > 0 }}
    steps:
      - name: RSS issues
        uses: guilhem/rss-issues-action@0.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          feed: 'https://github.com/Kengxxiao/ArknightsGameData/commits.atom'
          labels: update
          lastTime: '2h'
      - name: Sleep
        run: sleep 10
      - name: Close issues
        uses: Tsuk1ko/close-matching-issues@v2
        id: close-issue
        with:
          query: 'state:open author:app/github-actions'
          token: ${{ secrets.GITHUB_TOKEN }}
  update:
    needs: check
    if: needs.check.outputs.need-update == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://${{ secrets.AUTHENTICATION }}@github.com/arkntools/arknights-toolbox.git . --single-branch --depth=1
          git config user.name "アーミヤ"
          git config user.email "amiya@rhodes.island"
      - name: Checkout game data
        run: |
          git clone https://github.com/Kengxxiao/ArknightsGameData.git ../ArknightsGameData --single-branch --depth=1
          git clone https://github.com/Dimbreath/ArknightsData.git ../ArknightsData --single-branch --depth=1
      - name: Update data
        id: update
        run: |
          yarn install --frozen-lockfile
          IFTTT_EVENT_KEY=${{ secrets.IFTTT_EVENT_KEY }} yarn run update-data:local
      - name: Push
        run: |
          git add -A
          git commit -m "ドクター、終わってない仕事がたくさんありますから。まだ休んじゃダメですよ。" && git push || true
      - name: Retry update
        if: steps.update.outputs.need_retry == 'true'
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: '[RETRY] ${{ github.run_id }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: retry
          body: '[Link](../actions/runs/${{ github.run_id }})'
