name: Check for updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      need-update: ${{ steps.close-issue.outputs.num > 0 }}
    steps:
      - name: RSS issues
        uses: guilhem/rss-issues-action@0.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          feed: 'https://github.com/Kengxxiao/ArknightsGameData/commits.atom'
          labels: update
          lastTime: '2h'
      - name: Sleep
        run: sleep 30
      - name: Close issues
        uses: Tsuk1ko/close-matching-issues@v2
        id: close-issue
        with:
          query: 'state:open author:app/github-actions'
          token: ${{ secrets.GITHUB_TOKEN }}
  update:
    needs: check
    if: needs.check.outputs.need-update == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: arkntools/arknights-toolbox
          token: ${{ secrets.AUTHENTICATION }}
      - name: Config git
        run: |
          git config user.name "アーミヤ"
          git config user.email "amiya@rhodes.island"
      - name: Update data
        id: update
        run: |
          yarn install
          IFTTT_EVENT_KEY=${{ secrets.IFTTT_EVENT_KEY }} yarn run update-data
      - name: Push
        run: |
          git add -A
          git commit -m "ドクター、終わってない仕事がたくさんありますから。まだ休んじゃダメですよ。" && git push || true
      - name: Retry update
        if: steps.update.outputs.need_retry == 'true'
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: '[RETRY] ${{ github.run_id }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: retry
          body: '[Link](../actions/runs/${{ github.run_id }})'
